# Generated by Django 5.0 on 2023-12-06 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keepgreen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='name',
        ),
    ]
