# Generated by Django 5.0 on 2023-12-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keepgreen', '0005_alter_contact_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='keepGreen',
        ),
    ]
